<template>
  <v-container fluid class="ml-8">
    <section>
      <v-row no-gutters justify="center">
        <!-- <v-item-group> -->
        <v-row align-content="center" justify="center">
          <!-- Category button -->
          <v-col
            class="text-center"
            align-self="center"
            v-for="(n, index) in cat_details.slice(0, 7)"
            :key="index"
            cols="3"
            md="1"
          >
            <v-item class="category">
              <v-btn @click="goToCategory(n.categoryId)" color="#cc435e" text>{{
                n.name
              }}</v-btn>
            </v-item>
          </v-col>
        </v-row>

        <!-- Category details -->
        <!-- <v-col align-self="start" md="8">
          <div v-for="cat in mock_details.slice(2, 10)" :key="cat.categoryId">
            <h1>{{ cat.name }}</h1>
            <CardSwiper :slides="cat.card"></CardSwiper>
          </div>
        </v-col> -->
      </v-row>
    </section>
    <section class="pt-16">
      <v-row class="mx-16">
        <v-col
          v-for="(card, index) in mock_details.slice(-50)"
          :key="index"
          class="mx-0"
          cols="3"
        >
          <CardImage :card="card"> </CardImage>
        </v-col>
      </v-row>
    </section>
  </v-container>
</template>

<script>
// @ is an alias to /src
import { getAllCategoriesWithCards } from "@/api/CategoryApiServices";
// import { VueperSlides, VueperSlide } from "vueperslides";
import "vueperslides/dist/vueperslides.css";
import CardImage from "../components/CardImg";
// import CardSwiper from "../components/CardSwiper";
export default {
  name: "Home",
  components: {
    CardImage,
    // CardSwiper,
  },
  data() {
    return {
      pauseOnHover: true,
      autoPlaying: true,
      internalAutoPlaying: true,
      cat_details: [],
      mock_details: [
        {
          cardId: 432,
          name: "bear",
          description: "gấu",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 433,
          name: "chimpanzee",
          description: "hắc tinh tinh",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 434,
          name: "elephant",
          description: "voi",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 435,
          name: "fox",
          description: "cáo",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 436,
          name: "giraffe",
          description: "hươu cao cổ",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 437,
          name: "hippopotamus",
          description: "hà mã",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 438,
          name: "lion",
          description: "sư tử",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 439,
          name: "jaguar",
          description: "báo đốm",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 440,
          name: "porcupine",
          description: "nhím",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 441,
          name: "raccoon",
          description: "gấu mèo",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 442,
          name: "rhinoceros",
          description: "tê giác",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 443,
          name: "squirrel",
          description: "sóc",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 444,
          name: "alligator",
          description: "cá sấu",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 445,
          name: "bat",
          description: "dơi",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 446,
          name: "deer",
          description: "hươu",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 447,
          name: "wolf",
          description: "chó sói",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 448,
          name: "beaver",
          description: "hải ly",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 449,
          name: "chipmunk",
          description: "sóc chuột",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 450,
          name: "dolphin",
          description: "cá heo",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 451,
          name: "shark",
          description: "cá mập",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 452,
          name: "whale",
          description: "cá voi",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 453,
          name: "eel",
          description: "lươn",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 454,
          name: "swordfish",
          description: "cá kiếm",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 455,
          name: "walrus",
          description: "hải mã",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 456,
          name: "penguin",
          description: "chim cánh cụt",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 457,
          name: "turtle",
          description: "rùa",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 458,
          name: "antelope",
          description: "nai sừng tấm",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 459,
          name: "bee",
          description: "ong",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 460,
          name: "cobra",
          description: "rắn hổ mang",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 461,
          name: "camel",
          description: "lạc đà",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 462,
          name: "scorpion",
          description: "bọ cạp",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 463,
          name: "zebra",
          description: "ngựa vằn",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 464,
          name: "donkey",
          description: "lừa",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 465,
          name: "monkey",
          description: "khỉ",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 466,
          name: "cat",
          description: "mèo",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 467,
          name: "dog",
          description: "chó",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 468,
          name: "fish",
          description: "cá",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 469,
          name: "chicken",
          description: "gà",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 470,
          name: "duck",
          description: "vịt",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 471,
          name: "pig",
          description: "heo",
          imgUrl: null,
          categoryId: 1,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 472,
          name: "hot",
          description: "nóng",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 473,
          name: "cold",
          description: "lạnh",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 474,
          name: "hungry",
          description: "đói",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 475,
          name: "frustated",
          description: "bực bội",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 476,
          name: "furious",
          description: "điên tiết",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 477,
          name: "angry",
          description: "giận dữ",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 478,
          name: "disgusted",
          description: "ghê tởm",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 479,
          name: "surprised",
          description: "ngạc nhiên",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 480,
          name: "sad",
          description: "buồn bã",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 481,
          name: "bored",
          description: "chán",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 482,
          name: "scared",
          description: "sợ hãi",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 483,
          name: "sleepy",
          description: "buồn ngủ",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 484,
          name: "exhausted",
          description: "mệt mỏi",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 485,
          name: "shy",
          description: "e thẹn",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 486,
          name: "happy",
          description: "hạnh phúc",
          imgUrl: null,
          categoryId: 5,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 487,
          name: "daisy",
          description: "hoa cúc",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 488,
          name: "rose",
          description: "hoa hồng",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 489,
          name: "narcissus",
          description: "hoa thủy tiên",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 490,
          name: "orchild",
          description: "hoa phong lan",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 491,
          name: "tulip",
          description: "hoa tu lip",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 492,
          name: "sunflower",
          description: "hoa hướng dương",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 493,
          name: "cyclamen",
          description: "hoa anh thảo",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 494,
          name: "carnation",
          description: "hoa cẩm chướng",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 495,
          name: "poppy",
          description: "hoa anh túc",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 496,
          name: "pansy",
          description: "hoa păng sê",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 497,
          name: "violet",
          description: "hoa vi o lét",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 498,
          name: "mimosa",
          description: "hoa xấu hổ",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 499,
          name: "lily",
          description: "hoa loa kèn",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 500,
          name: "hyacinth",
          description: "hoa lan dạ hương",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 501,
          name: "gladiolus",
          description: "hoa lay ơn",
          imgUrl: null,
          categoryId: 9,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 502,
          name: "sweet",
          description: "ngọt",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 503,
          name: "salty",
          description: "mặn",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 504,
          name: "bitter",
          description: "đắng",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 505,
          name: "sour",
          description: "chua",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 506,
          name: "cheesy",
          description: "béo vị phô mai",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 507,
          name: "bland",
          description: "nhạt",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 508,
          name: "spicy",
          description: "cay",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 509,
          name: "garlicky",
          description: "vị tỏi",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 510,
          name: "smoky",
          description: "vị xông khói",
          imgUrl: null,
          categoryId: 11,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 511,
          name: "principal",
          description: "hiệu trưởng",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 512,
          name: "teacher",
          description: "giáo viên",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 513,
          name: "janitor",
          description: "lao công",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 514,
          name: "student",
          description: "học sinh",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 515,
          name: "classroom",
          description: "phòng học",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 516,
          name: "hall",
          description: "hội trường",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 517,
          name: "library",
          description: "thư viện",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 518,
          name: "canteen",
          description: "căn tin",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 519,
          name: "subjects",
          description: "môn học",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 520,
          name: "blackboard",
          description: "bảng đen",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 521,
          name: "projector",
          description: "máy chiếu",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 522,
          name: "computer",
          description: "máy vi tính",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 523,
          name: "campus",
          description: "khuôn viên trường",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 524,
          name: "dormitory",
          description: "ký túc xá",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 525,
          name: "lecturer",
          description: "giảng viên",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 526,
          name: "professor",
          description: "giáo sư",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 527,
          name: "cafeteria",
          description: "quán ăn tự phục vụ",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 528,
          name: "thesis",
          description: "khóa luận",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 529,
          name: "laboratory",
          description: "phòng thí nghiệm",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 530,
          name: "infirmary",
          description: "phòng y tế",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 531,
          name: "schoolyard",
          description: "sân trường",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 532,
          name: "staffroom",
          description: "phòng giáo viên",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 533,
          name: "test",
          description: "bài kiểm tra",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 534,
          name: "textbook",
          description: "sách giáo khoa",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 535,
          name: "timetable",
          description: "thời khóa biểu",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 536,
          name: "uniform",
          description: "đồng phục",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 537,
          name: "yearbook",
          description: "kỷ yếu",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 538,
          name: "homework",
          description: "bài tập về nhà",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 539,
          name: "bell",
          description: "chuông",
          imgUrl: null,
          categoryId: 13,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 540,
          name: "car",
          description: "xe hơi",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 541,
          name: "truck",
          description: "xe tải",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 542,
          name: "bus",
          description: "xe buýt",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 543,
          name: "bicycle",
          description: "xe đạp",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 544,
          name: "scooter",
          description: "xe tay ga",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 545,
          name: "motorbike",
          description: "xe máy",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 546,
          name: "train",
          description: "xe lửa",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 547,
          name: "subway",
          description: "tàu điện ngầm",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 548,
          name: "jet",
          description: "máy bay phản lực",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 549,
          name: "submarine",
          description: "tàu cánh ngầm",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 550,
          name: "rocket",
          description: "tên lửa",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 551,
          name: "helicopter",
          description: "máy bay trực thăng",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 552,
          name: "sailboat",
          description: "thuyền buồm",
          imgUrl: null,
          categoryId: 15,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 553,
          name: "sun",
          description: "mặt trời",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 554,
          name: "mercury",
          description: "sao thủy",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 555,
          name: "venus",
          description: "sao kim",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 556,
          name: "earth",
          description: "trái đất",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 557,
          name: "mars",
          description: "sao hỏa",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 558,
          name: "jupiter",
          description: "sao mộc",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 559,
          name: "saturn",
          description: "sao thổ",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 560,
          name: "uranus",
          description: "sao thiên vương",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 561,
          name: "neptune",
          description: "sao hải vương",
          imgUrl: null,
          categoryId: 4,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 562,
          name: "stadium",
          description: "sân vận động",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 563,
          name: "pitch",
          description: "sân bóng đá",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 564,
          name: "scoreboard",
          description: "bảng điểm",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 565,
          name: "goal",
          description: "khung thành",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 566,
          name: "striker",
          description: "tiền đạo",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 567,
          name: "defender",
          description: "hậu vệ",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 568,
          name: "Goalkeeper",
          description: "thủ môn",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 569,
          name: "Referee",
          description: "trọng tài",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 570,
          name: "coach",
          description: "huấn luyện viên",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 571,
          name: "whistle",
          description: "còi",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 572,
          name: "trophy",
          description: "cúp",
          imgUrl: null,
          categoryId: 7,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 573,
          name: "astronaut",
          description: "phi hành gia",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 574,
          name: "cartoonist",
          description: "họa sĩ vẽ phim hoạt hình",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 575,
          name: "architect",
          description: "kiến trúc sư",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 576,
          name: "photographer",
          description: "nhiếp ảnh gia",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 577,
          name: "lawyer",
          description: "luật sư",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 578,
          name: "psychologist",
          description: "nhà tâm lý học",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 579,
          name: "model",
          description: "người mẫu",
          imgUrl: null,
          categoryId: 10,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 580,
          name: "cycling",
          description: "môn đạp xe",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 581,
          name: "gymnastics",
          description: "môn thể dục dụng cụ",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 582,
          name: "tennis",
          description: "môn quần vợt",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 583,
          name: "running",
          description: "môn chạy bộ",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 584,
          name: "swimming",
          description: "môn bơi lội",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 585,
          name: "riding",
          description: "môn cưỡi ngựa",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 586,
          name: "volleyball",
          description: "môn bóng chuyền",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 587,
          name: "football",
          description: "môn bóng đá",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 588,
          name: "basketball",
          description: "môn bóng rổ",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 589,
          name: "baseball",
          description: "môn bóng chày",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 590,
          name: "golf",
          description: "môn đánh golf",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 591,
          name: "slkateboarding",
          description: "môn trượt ván",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 592,
          name: "badminton",
          description: "môn cầu lông",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 593,
          name: "skiing",
          description: "môn trượt tuyết",
          imgUrl: null,
          categoryId: 12,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 594,
          name: "dress",
          description: "đầm",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 595,
          name: "blouse",
          description: "áo cánh",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 596,
          name: "pants",
          description: "quần tây",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 597,
          name: "shorts",
          description: "quần đùi",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 598,
          name: "shirt",
          description: "áo sơ mi",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 599,
          name: "suit",
          description: "đồ vest",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 600,
          name: "jacket",
          description: "áo khoác",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 601,
          name: "skirt",
          description: "váy",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 602,
          name: "cardigan",
          description: "áo khoác len",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 603,
          name: "sweeter",
          description: "áo len dài tay",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 604,
          name: "bathrobe",
          description: "áo choàng tắm",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 605,
          name: "jeans",
          description: "quần jeans",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 606,
          name: "nightdress",
          description: "đầm ngủ",
          imgUrl: null,
          categoryId: 14,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 607,
          name: "clasp",
          description: "cái gài",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 608,
          name: "chain",
          description: "chuỗi vòng cổ",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 609,
          name: "pendant",
          description: "mặt dây chuyền đá quý",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 610,
          name: "medallion",
          description: "mặt dây chuyền kim loại",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 611,
          name: "bangle",
          description: "vòng tay",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 612,
          name: "earrings",
          description: "bông tai",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 613,
          name: "pin",
          description: "gim cài áo",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 614,
          name: "cufflink",
          description: "khuy cài cổ tay áo",
          imgUrl: null,
          categoryId: 16,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 615,
          name: "magic",
          description: "phim kỳ ảo",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 616,
          name: "drama",
          description: "kịch",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 617,
          name: "comedy",
          description: "hài kịch",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 618,
          name: "cartoon",
          description: "hoạt hình",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 619,
          name: "horror",
          description: "phim kinh dị",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 620,
          name: "romantic",
          description: "phim tình cảm",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 621,
          name: "detective",
          description: "phim trinh thám",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 622,
          name: "thriller",
          description: "phim ly kỳ",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 623,
          name: "action",
          description: "phim hành động",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 624,
          name: "adventure",
          description: "phim phiêu lưu",
          imgUrl: null,
          categoryId: 6,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 625,
          name: "cobalt",
          description: "màu xanh cô ban",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 626,
          name: "beige",
          description: "màu be",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 627,
          name: "crimson",
          description: "màu đỏ thẫm",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 628,
          name: "indigo",
          description: "màu chàm",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 629,
          name: "jade",
          description: "màu xanh ngọc bích",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 630,
          name: "mauve",
          description: "màu tím hoa cà",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 631,
          name: "charcoal",
          description: "màu xám đậm",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 632,
          name: "maroon",
          description: "màu nâu đỏ",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 633,
          name: "purple",
          description: "màu tía",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 634,
          name: "silver",
          description: "màu xám bạc",
          imgUrl: null,
          categoryId: 8,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 635,
          name: "science",
          description:
            "a department of systematized knowledge that is an object of study; especially : one of the natural sciences (as biology, physics, or chemistry)",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 636,
          name: "science fair",
          description:
            "an exhibition of science projects typically prepared and presented by schoolchildren",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 637,
          name: "science fiction",
          description:
            "fiction dealing with the impact of actual or imagined science on society or individuals or having a scientific factor as an essential component of the plot",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 638,
          name: "Christian Science",
          description:
            "a religion and system of healing founded by Mary Baker Eddy and taught by the Church of Christ, Scientist",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 639,
          name: "computer science",
          description:
            "a branch of science that deals with the theory of computing or the design of computers",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 640,
          name: "creation science",
          description:
            "creationism; also : scientific evidence or arguments put forth in support of creationism",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 641,
          name: "domestic science",
          description:
            "instruction in domestic management and the household arts (as cooking and sewing)",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 642,
          name: "earth science",
          description:
            "any of the sciences (as geology, meteorology, or oceanography) that deal with the earth or with one or more of its parts",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 643,
          name: "exact science",
          description:
            "a science (as physics, chemistry, or astronomy) whose laws are capable of expression in accurately measured quantities",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 644,
          name: "life science",
          description:
            "a branch of science (as biology, medicine, and sometimes anthropology or sociology) that deals with living organisms and life processes",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 645,
          name: "coin:1",
          description:
            "a piece of metal issued by governmental authority as money",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 646,
          name: "coin:2",
          description: "to make (a coin) especially by stamping : mint",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 647,
          name: "coin:3",
          description: "of or relating to coins",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 648,
          name: "virus",
          description:
            "any of a large group of submicroscopic infective agents that are considered by some to be living simple microorganisms and by others to be complex molecules, that typically contain a protein coat surrounding an RNA or DNA core of genetic material but no s",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 649,
          name: "AIDS virus",
          description: "hiv",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 650,
          name: "filterable virus",
          description:
            "any of the infectious agents that remain infectious after passing through a filter with pores too fine for a bacterium to pass through",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 651,
          name: "human immunodeficien",
          description: "hiv",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 652,
          name: "West Nile virus",
          description:
            "a virus that causes an illness marked by fever, headache, muscle ache, skin rash, and sometimes encephalitis or meningitis and that is spread especially from birds to humans by mosquitos",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 653,
          name: "HIV",
          description:
            "any of a group of retroviruses that infect and destroy helper T cells of the immune system causing the marked reduction in their numbers that is diagnostic of AIDS —called also AIDS virus, human immunodeficiency virus",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
        {
          cardId: 654,
          name: "poliovirus",
          description:
            "a virus that causes human poliomyelitis and occurs in several distinct forms",
          imgUrl: null,
          categoryId: null,
          userId: 15,
          pronun: null,
          user: null,
          cardSet: [],
          userCard: [],
        },
      ],
    };
  },
  mounted() {
    getAllCategoriesWithCards().then((res) => {
      let name = res.data;
      this.cat_details = name;
    });
    console.log(this.getCatCards(1));
  },
  methods: {
    goToCategory(id) {
      this.$router
        .push({
          name: "CategoryView",
          params: { id: id },
        })
        .catch(() => {});
    },
    getCatCards(cat_id) {
      return this.cat_details.find((cat) => cat.categoryId == cat_id);
    },
  },
  computed: {
    categories: function() {
      return this.cat_details.map((cat) => cat.name);
    },
  },
};
</script>
<style scoped>
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,700;1,400&display=swap");
div,
h1 {
  font-family: "Open Sans", sans-serif;
}
.category {
  text-decoration: none;
  color: #000;
  font-weight: 500;
  font-style: italic;
}

/* .category:hover {
  padding: 10px;
  font-weight: 100;
  border: 1px solid #cc435e;
  background-color: #cc435e;
  border-radius: 10px; 
} */
</style>
